version: "3.8"
services:
  sqldb:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  web:
    build: ./src
    restart: always
    command: bash entry_point.sh
    volumes:
      - .:/code
    environment: 
      - FLASK_APP=api
      - FLASK_DEBUG=1
    ports:
      - 5000:5000
    depends_on:
      - sqldb

