"""empty message

Revision ID: 07757ae10e36
Revises: 65dd305025f9
Create Date: 2020-11-24 18:19:25.674946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07757ae10e36'
down_revision = '65dd305025f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('request', 'active')
    # ### end Alembic commands ###
