"""empty message

Revision ID: 818aac47b78c
Revises: 07757ae10e36
Create Date: 2020-11-25 01:44:47.533806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818aac47b78c'
down_revision = '07757ae10e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
