"""empty message

Revision ID: dadb4285d3fd
Revises: 26dfa56c649f
Create Date: 2020-11-24 17:54:02.422354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadb4285d3fd'
down_revision = '26dfa56c649f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'available')
    # ### end Alembic commands ###
